"""Add PPMEquipment model

Revision ID: 34d25f5c0e1a
Revises: 
Create Date: 2025-06-27 15:01:15.560048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d25f5c0e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppm_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('log_number', sa.String(length=50), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ppm_q1_engineer', sa.String(length=100), nullable=True),
    sa.Column('ppm_q1_date', sa.Date(), nullable=True),
    sa.Column('ppm_q1_status', sa.String(length=50), nullable=True),
    sa.Column('ppm_q2_engineer', sa.String(length=100), nullable=True),
    sa.Column('ppm_q2_date', sa.Date(), nullable=True),
    sa.Column('ppm_q2_status', sa.String(length=50), nullable=True),
    sa.Column('ppm_q3_engineer', sa.String(length=100), nullable=True),
    sa.Column('ppm_q3_date', sa.Date(), nullable=True),
    sa.Column('ppm_q3_status', sa.String(length=50), nullable=True),
    sa.Column('ppm_q4_engineer', sa.String(length=100), nullable=True),
    sa.Column('ppm_q4_date', sa.Date(), nullable=True),
    sa.Column('ppm_q4_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppm_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppm_equipment_serial'), ['serial'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppm_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppm_equipment_serial'))

    op.drop_table('ppm_equipment')
    # ### end Alembic commands ###
