"""Add OCM equipment model

Revision ID: 98716cbc2678
Revises: 1234567890ab
Create Date: 2025-06-27 16:00:57.127278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98716cbc2678'
down_revision = '1234567890ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocm_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('log_number', sa.String(length=50), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('engineer', sa.String(length=100), nullable=True),
    sa.Column('next_maintenance', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocm_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocm_equipment_serial'), ['serial'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocm_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocm_equipment_serial'))

    op.drop_table('ocm_equipment')
    # ### end Alembic commands ###
